server:
#  port: 2222
   port: 2223
spring:
  application:
    name: eureka-ribbon-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost